
dset:
  path: hate-speech/
  binary_labels: true

ml:
  img:
    hog:
      block_size: [[8, 8], [16, 16], [32, 32]]
      block_stride: [[4, 4], [8, 8], [16, 16]]
      cell_size: [[4, 4], [8, 8], [16, 16]]
      nbins: [6, 9, 12, 18] 
    bovw:
      k: [50, 100, 200, 500]  
  txt:
    tf:
      max_features: [500, 1000, 5000, 10000]
      max_df: [0.75, 0.85, 1.0] 
      use_idf: [True, False] 
    w2v:
      vector_size: [10,20,50] 
      window: [3, 5, 7] 
      min_count: [1, 5, 10] 
      sg: [0, 1]
  models:
    knn:
      n_neighbors: [3, 5, 10, 15, 20]
    rf:
      n_estimators: [50, 100, 200, 500]  
      criterion: ["gini", "entropy"]
      max_depth: [None, 10, 20, 30, 50, 100]
      min_samples_split: [2, 5, 10] 
      min_samples_leaf: [1, 2, 5, 10] 
      max_features: ["auto", "sqrt", "log2"] 